# Generated by Django 3.0.8 on 2020-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrarapidlinks', '0006_auto_20200826_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storedurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
