# Generated by Django 3.0.8 on 2020-08-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrarapidlinks', '0007_auto_20200827_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedurl',
            name='updated',
        ),
    ]
